# Project: 專案1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = Ch9_2.o Ch9_2_1.o
LINKOBJ  = Ch9_2.o Ch9_2_1.o
LIBS     = -L"F:/Dev C++/DevCppPortable/MinGW64/lib" -L"F:/Dev C++/DevCppPortable/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"F:/Dev C++/DevCppPortable/MinGW64/include" -I"F:/Dev C++/DevCppPortable/MinGW64/x86_64-w64-mingw32/include" -I"F:/Dev C++/DevCppPortable/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"F:/Dev C++/DevCppPortable/MinGW64/include" -I"F:/Dev C++/DevCppPortable/MinGW64/x86_64-w64-mingw32/include" -I"F:/Dev C++/DevCppPortable/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"F:/Dev C++/DevCppPortable/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = 專案1.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

Ch9_2.o: Ch9_2.cpp
	$(CPP) -c Ch9_2.cpp -o Ch9_2.o $(CXXFLAGS)

Ch9_2_1.o: Ch9_2_1.cpp
	$(CPP) -c Ch9_2_1.cpp -o Ch9_2_1.o $(CXXFLAGS)
